### ISSUE TITLE
Feature Request: Interception of calls to built-in resources and bundles in Unity-games

### ISSUE THREAD

**Issue by Albeoris** [Reloaded-Project/Reloaded.Mod.Universal.Redirector#1]
One of the common problems when modifying Unity games is serialized MonoBehaviors.

Assets such as Sprite and Texture2D can be found in their fields.
These assets are deserialized by the built-in Unity methods that are tied to a specific version of the Unity Engine, bypassing .NET (that is, they do not call methods like `Resource.Load`).

It would be great to have a hook that catches any calls to resources in bundles. Like:
```c#
void AfterResourceLoaded (String bundleName, String assetPath, ref Unity.Object resource); 
```

**Comment by Sewer56** [comment]
I'm don't believe this falls within the scope of this repository. 

The goal of this modification specifically is to redirect file handle requests from 1 file on disk to instead be performed using another file; such that a file can be replaced with another file entirely at runtime. While I could see something like [faking file search results](https://docs.microsoft.com/en-us/windows/win32/fileio/listing-the-files-in-a-directory) being part of this project, the goal of this project isn't to handle remapping slices of files to slices of other files.

Although such experiments have been performed using Reloaded [[1](https://github.com/Sewer56/AfsFsRedir.ReloadedII)] [[2](https://github.com/TGEnigma/p4gpc.modloader)]

Additional question:
If you're working with a .NET based Unity project, wouldn't using something like [BepinEx](https://github.com/BepInEx/BepInEx) and [HarmonyX](https://github.com/BepInEx/HarmonyX) be easier for the task? Then directly hook into the Unity code.

**Comment by Albeoris** [comment]
> I'm don't believe this falls within the scope of this repository.

Feel free to close the issue. :)

> If you're working with a .NET based Unity project, wouldn't using something like BepinEx and HarmonyX be easier for the task? 

Unfortunately, it's impossble. Unity does not use .NET code, but native libraries to load serialized objects. That is the problem.

We can intercept the loading of dynamic resources using Harmony and BeepInEx, but static resources (Scene Components, MonoBehaviour, ScriptableObject) are serialized bypassing the .NET API. :(

And we can't just write a mini-filter around CreateFile, as the bundle format is complex and changes with every version of Unity.

**Comment by Sewer56** [comment]
> Although such experiments have been performed using Reloaded [[1](https://github.com/Sewer56/AfsFsRedir.ReloadedII)] [[2](https://github.com/TGEnigma/p4gpc.modloader)]

You should look at these for inspiration on how to emulate an archive format at the Windows API level. 
Alternatively take the approach of hooking native internal Unity functions, by finding them and then using function signatures to find them.

Whichever direction you take, if the format frequently changes, you'll need to update your code to handle the cases accordingly.

**Comment by Albeoris** [comment]
@Sewer56 , one more question - can I use Reloaded.Hooks or Reloaded.Universal.Redirector to hook NtFileCreate directly from BeepInEx without Reloaded Application?

**Comment by Sewer56** [comment]
`Reloaded.Hooks` is the hooking library. 
`Reloaded.Universal.Redirector` is a mod for Reloaded-II.

You probably want to just copy the code from `Reloaded.Universal.Redirector` from the following places:
https://github.com/Reloaded-Project/reloaded.universal.redirector/blob/master/Reloaded.Universal.Redirector/FileAccessServer.cs
https://github.com/Reloaded-Project/reloaded.universal.redirector/blob/master/Reloaded.Universal.Redirector/Native.cs

And modify it a bit.
